### ISSUE TITLE
Website feedback on Thursday at 18:30

### ISSUE THREAD

**Issue by yannhermouet** [ShuttleProject/ShuttleProject.github.io#2]
@m-maillot I put back my feedback here, in an issue it will be easier:
Pour le site:
- In the `NavBar` section, the Shuttle Logo in th enavbar needs to be the round edition.
- In the `NavBar` section, The`Shuttle` text right to the logo in the navbar needs to be bigger.
- In the `NavBar` section, should we add the social buttons found in the `Footer`?
- The section `Mobile build distribution made easy;)` with the big logo cleary doesn't work (I know I took my time). Switch to #F9F9FB (color of the `Features` section for what I get in the inspector and also the a color used in Shuttle itself).
- Changing the `Mobile build distribution made easy;)` by ` Apps management and distribution made easy;)`
- We change the color text of: `Mobile build distribution made easy;)` either as #2B2F3 (which looks like the text primary color), or #4093FC (the logo color), or #80B9FF (or the blue from the `underligne`: #82bafc). They need to be tested once the section background has changed.
- In the `Features` section, adding the new schematics (Yeah!) and maybe changing how this section looks...
- What to do of the  `Demo` section while we don't have the video. The new screenshots from Mus? Changing the "Demo" name for "Clean UI"?
- The `Case Study` Tabs are better this way and centered which is nicer. I think the lines need to be extended on both sides. Text needs more spacing. Animations needs better/different timing.
- In the `Support` section, the email address needs to be at the end of the line.
- In the `Footer`, the `Made with...` needs to be the same as the ReadMe.
- Overall text check based on the ReadMe
Everything else looks really good!!!

**Comment by yannhermouet** [comment]
- Top Header white, following sections, grey/white alternate

**Comment by m-maillot** [comment]
Done is PR above
